/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactions.HesapBilgileri;
import database.transactions.KullaniciBasvuru;
import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButtonAyarlari;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.TextAyarlari;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author emrecan
 */
public class BasvuruEkrani extends javax.swing.JFrame implements IDuzenleyici, IBilgiController {

    private KullaniciBasvuru kullaniciBasvuruObject = null;

    /**
     * Creates new form BasvuruEkrani
     */
    public BasvuruEkrani() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basvuruEkraniPanel = new javax.swing.JPanel();
        lblGuvenlikBilgileri = new javax.swing.JLabel();
        lblAdSoyad = new javax.swing.JLabel();
        txtAdSoyad = new javax.swing.JTextField();
        txtTcNo = new javax.swing.JTextField();
        lblTc = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        lblguvenlikSorusu = new javax.swing.JLabel();
        lblKisiselBilgiler1 = new javax.swing.JLabel();
        lblTelefon1 = new javax.swing.JLabel();
        cmbGuvenlik = new javax.swing.JComboBox<>();
        txtCevap = new javax.swing.JTextField();
        lblGuvenlikCevap = new javax.swing.JLabel();
        btnBasvur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sweet Bank - Başvuru Ekranı");
        setPreferredSize(new java.awt.Dimension(523, 549));
        setResizable(false);

        basvuruEkraniPanel.setBackground(new java.awt.Color(255, 255, 204));

        lblGuvenlikBilgileri.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblGuvenlikBilgileri.setText("Güvenlik Bilgileri");

        lblAdSoyad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAdSoyad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdSoyad.setText("Ad Soyad :");

        txtAdSoyad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtTcNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblTc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTc.setText("T.C. No :");

        txtTelefon.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblguvenlikSorusu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblguvenlikSorusu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblguvenlikSorusu.setText("Güvenlik Sorusu :");

        lblKisiselBilgiler1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblKisiselBilgiler1.setText("Kişisel Bilgiler");

        lblTelefon1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTelefon1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefon1.setText("Telefon No:");

        cmbGuvenlik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evcil hayvanınızın adı nedir?", "En sevdiğiniz nesne nedir?", "İlkokul öğretmeninizin soyadı nedir?", "Yaşamak istediğiniz yer neresidir?", "İstediğiniz bir cümle girin.(önerilir)" }));

        txtCevap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblGuvenlikCevap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblGuvenlikCevap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGuvenlikCevap.setText("Cevap :");

        btnBasvur.setBackground(new java.awt.Color(204, 204, 255));
        btnBasvur.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBasvur.setText("Başvur");
        btnBasvur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBasvur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBasvurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBasvurMouseExited(evt);
            }
        });
        btnBasvur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasvurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basvuruEkraniPanelLayout = new javax.swing.GroupLayout(basvuruEkraniPanel);
        basvuruEkraniPanel.setLayout(basvuruEkraniPanelLayout);
        basvuruEkraniPanelLayout.setHorizontalGroup(
            basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                        .addComponent(lblGuvenlikCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnBasvur, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTelefon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAdSoyad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                            .addComponent(lblguvenlikSorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbGuvenlik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblGuvenlikBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(lblKisiselBilgiler1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        basvuruEkraniPanelLayout.setVerticalGroup(
            basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTcNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(lblGuvenlikBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblguvenlikSorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGuvenlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuvenlikCevap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBasvur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(basvuruEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvuruEkraniPanelLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(lblKisiselBilgiler1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );

        basvuruEkraniPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbGuvenlik, lblguvenlikSorusu});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basvuruEkraniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBasvurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBasvurMouseEntered
        ButtonAyarlari.setBgFg(btnBasvur, Color.black, Color.white);
    }//GEN-LAST:event_btnBasvurMouseEntered

    private void btnBasvurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBasvurMouseExited
        ButtonAyarlari.setOriginalBgFg(btnBasvur);
    }//GEN-LAST:event_btnBasvurMouseExited

    private void btnBasvurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasvurActionPerformed
        if (this.bilgilerGecerliMi()) {
            basvuruyuGerceklestir();
        } else {
            Dialogs.bosOlamazMesajiGoster(this);
        }
    }//GEN-LAST:event_btnBasvurActionPerformed

    private void basvuruyuGerceklestir() {

        //Kişisel Bilgiler
        this.getKullaniciBasvuruObject().setAdSoyad(this.txtAdSoyad.getText().trim());
        this.getKullaniciBasvuruObject().setTcNo(this.txtTcNo.getText());
        this.getKullaniciBasvuruObject().setTelNo(this.txtTelefon.getText());

        //Güvenlik Bilgileri
        this.getKullaniciBasvuruObject().setGuvenlikSorusu(String.valueOf(this.cmbGuvenlik.getSelectedItem()));
        this.getKullaniciBasvuruObject().setGuvenlikCevap(this.txtCevap.getText().trim());

        //Sistem Bilgileri
        this.getKullaniciBasvuruObject().setMusteriNo(this.randomMusteriNoAl());
        this.getKullaniciBasvuruObject().setSifre(this.randomSifreAl());

        if (this.getKullaniciBasvuruObject().basvuruOnaylandiMi()) {
            Dialogs.ozelMesajGoser(this, "Başvurunuz kabul edilmiştir...\n"
                    + "Müşteri No :" + this.getKullaniciBasvuruObject().getMusteriNo()
                    + "\nŞifreniz :" + this.getKullaniciBasvuruObject().getSifre());
            ActionAyarlari.setVisible(this, new GirisEkrani());
        } else {
            Dialogs.ozelMesajGoser(this, "Başvurunuz kabul edilmemiştir!\n"
                    + "Lütfen bilgilerini kontrol edin...");
        }

    }

    private String randomMusteriNoAl() {

        String musteriNo;
        do {
            musteriNo = String.valueOf(100000 + (int) (Math.random() * 9000000));
        } while (this.getKullaniciBasvuruObject().musteriNoTablodaVarMi());
        return musteriNo;
    }

    private String randomSifreAl() {
        String sifre;
        sifre = String.valueOf(1000 + (int) (Math.random() * 9000));
        return sifre;
    }

    /**
     * @param args the command line arguments
     */
    @Override
    public void getEdits() {

        this.setLocationRelativeTo(null);
        basvuruEkraniPanel.setFocusable(true);
        TextAyarlari.setOnlyAlphabetic(txtAdSoyad);
        TextAyarlari.setOnlyNumber(txtTcNo);
        TextAyarlari.setOnlyNumber(txtTelefon);
        TextAyarlari.setMaxLimit(txtTcNo, 11);
        TextAyarlari.setMaxLimit(txtTelefon, 11);

    }

    public KullaniciBasvuru getKullaniciBasvuruObject() {
        if (this.kullaniciBasvuruObject == null) {
            kullaniciBasvuruObject = new KullaniciBasvuru();
        }
        return kullaniciBasvuruObject;
    }

    @Override
    public boolean bilgilerGecerliMi() {
        return TextAyarlari.textAlanlariDoluMu(basvuruEkraniPanel);
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return HesapBilgileri.getInstance();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasvuruEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasvuruEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basvuruEkraniPanel;
    private javax.swing.JButton btnBasvur;
    private javax.swing.JComboBox<String> cmbGuvenlik;
    private javax.swing.JLabel lblAdSoyad;
    private javax.swing.JLabel lblGuvenlikBilgileri;
    private javax.swing.JLabel lblGuvenlikCevap;
    private javax.swing.JLabel lblKisiselBilgiler1;
    private javax.swing.JLabel lblTc;
    private javax.swing.JLabel lblTelefon1;
    private javax.swing.JLabel lblguvenlikSorusu;
    private javax.swing.JTextField txtAdSoyad;
    private javax.swing.JTextField txtCevap;
    private javax.swing.JTextField txtTcNo;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

}
