/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgiController;
import database.transactions.HesapBilgileri;
import database.transactions.ParaYatirma;
import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.Dialogs;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.TextAyarlari;

/**
 *
 * @author emrecan
 */
public class ParaYatirmaEkrani extends javax.swing.JFrame implements IDuzenleyici, IBilgiController{
    
    private int yatirilacakMiktar = 0;
    private ParaYatirma paraYatirmaObject = null;

    /**
     * Creates new form ParaYatirmaEkrani
     */
    public ParaYatirmaEkrani() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paraYatirmaEkraniPanel = new javax.swing.JPanel();
        lblKullaniciAdiSoyadi = new javax.swing.JLabel();
        lblLimitUyari = new javax.swing.JLabel();
        lblToplamBakiyeniz = new javax.swing.JLabel();
        lblBakiye = new javax.swing.JLabel();
        lblYatiracaginizMiktar = new javax.swing.JLabel();
        txtYatirilacakMiktar = new javax.swing.JTextField();
        btnParaYatir = new javax.swing.JButton();
        previousIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(581, 435));
        setResizable(false);

        paraYatirmaEkraniPanel.setBackground(new java.awt.Color(255, 255, 204));

        lblKullaniciAdiSoyadi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKullaniciAdiSoyadi.setForeground(new java.awt.Color(255, 0, 0));
        lblKullaniciAdiSoyadi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKullaniciAdiSoyadi.setText("Sayın [KULLANICI ADI SOYADI]");

        lblLimitUyari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLimitUyari.setText("Tek seferde 40.000 TL ve altını yatırabilirsiniz.");

        lblToplamBakiyeniz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblToplamBakiyeniz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblToplamBakiyeniz.setText("Toplam Bakiyeniz :");

        lblBakiye.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBakiye.setText("[BAKİYE]");

        lblYatiracaginizMiktar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYatiracaginizMiktar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYatiracaginizMiktar.setText("Yatıracağınız Miktar :");

        txtYatirilacakMiktar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtYatirilacakMiktar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYatirilacakMiktarKeyReleased(evt);
            }
        });

        btnParaYatir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnParaYatir.setText("Para Yatır");
        btnParaYatir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParaYatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParaYatirActionPerformed(evt);
            }
        });

        previousIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/previousIcon.png"))); // NOI18N
        previousIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        previousIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paraYatirmaEkraniPanelLayout = new javax.swing.GroupLayout(paraYatirmaEkraniPanel);
        paraYatirmaEkraniPanel.setLayout(paraYatirmaEkraniPanelLayout);
        paraYatirmaEkraniPanelLayout.setHorizontalGroup(
            paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                        .addComponent(lblYatiracaginizMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtYatirilacakMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                        .addComponent(lblToplamBakiyeniz, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                .addGroup(paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblLimitUyari))
                    .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblKullaniciAdiSoyadi))
                    .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previousIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paraYatirmaEkraniPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnParaYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        paraYatirmaEkraniPanelLayout.setVerticalGroup(
            paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paraYatirmaEkraniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousIcon)
                .addGap(33, 33, 33)
                .addComponent(lblKullaniciAdiSoyadi)
                .addGap(45, 45, 45)
                .addComponent(lblLimitUyari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToplamBakiyeniz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paraYatirmaEkraniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYatiracaginizMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYatirilacakMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParaYatir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paraYatirmaEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paraYatirmaEkraniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void getEdits() {
       this.setLocationRelativeTo(null);
       paraYatirmaEkraniPanel.setFocusable(true);
       TextAyarlari.setOnlyNumber(txtYatirilacakMiktar);
       TextAyarlari.setMaxLimit(txtYatirilacakMiktar, 5);
       this.lblKullaniciAdiSoyadi.setText("Sayın "+this.getHesapBilgileri().getAdSoyad());
       this.lblBakiye.setText(String.valueOf(getHesapBilgileri().getBakiye()));
    }

    @Override
    public boolean bilgilerGecerliMi() {
        return !(this.txtYatirilacakMiktar.getText().equals(""));
    }

    @Override
    public HesapBilgileri getHesapBilgileri() {
        return HesapBilgileri.getInstance();
    }

    public ParaYatirma getParaYatirmaObject() {
        if (this.paraYatirmaObject==null) {
            paraYatirmaObject = new ParaYatirma();
        }
        return paraYatirmaObject;
    }

    
    
    
    private void txtYatirilacakMiktarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYatirilacakMiktarKeyReleased
        this.yatirilacakMiktar = TextAyarlari.checkTextKeyReleased(txtYatirilacakMiktar, 40000);
    }//GEN-LAST:event_txtYatirilacakMiktarKeyReleased

    private void btnParaYatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaYatirActionPerformed
        if (this.bilgilerGecerliMi()) {
            this.paraYatir();
        }else{
            Dialogs.bosOlamazMesajiGoster(this);
        }
    }//GEN-LAST:event_btnParaYatirActionPerformed

    private void paraYatir() {
        this.getParaYatirmaObject().setYatirilacakMiktar(this.yatirilacakMiktar);
        
        if (getParaYatirmaObject().paraYatirildiMi()) {
            Dialogs.ozelMesajGoser(this, "Para Başarıyla Hesabınıza Yatırıldı...\n"
                    + "Yatırılan Miktar:"+this.yatirilacakMiktar+" TL");
            ActionAyarlari.setVisible(this, new HesapEkrani());
        }
        else{
            Dialogs.ozelMesajGoser(this, "Bilgilerinizi Kontrol Edin!");
        }
    }
    
    private void previousIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousIconMouseClicked
        ActionAyarlari.setVisible(this, new HesapEkrani());
    }//GEN-LAST:event_previousIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParaYatirmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParaYatirmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParaYatirmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParaYatirmaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParaYatirmaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParaYatir;
    private javax.swing.JLabel lblBakiye;
    private javax.swing.JLabel lblKullaniciAdiSoyadi;
    private javax.swing.JLabel lblLimitUyari;
    private javax.swing.JLabel lblToplamBakiyeniz;
    private javax.swing.JLabel lblYatiracaginizMiktar;
    private javax.swing.JPanel paraYatirmaEkraniPanel;
    private javax.swing.JLabel previousIcon;
    private javax.swing.JTextField txtYatirilacakMiktar;
    // End of variables declaration//GEN-END:variables
}
